title: <p align="center"> Muhammad Asif Khan </p> # your name (or website title) here
logo: "/images/best.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="justify">
  I am a hardworking, passionate, and  fast learning individual who is currently seeking to change my professional career from teaching to Data Science. 
  <br><br>
  I am currently enrolled in a MS degree in Big Data Analytics at North Wales Management School, Wrexham Glyndwr University.
  <br><br>
  I am very interested in solving Big Data problems in finance and healthcare by using modern tools and technologies of Machine Learning and Artificial Intelligence. 
  <br><br>
  </p>
  <a href="https://www.linkedin.com/in/akhandatascience">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
