title: <p align="center"> Muhammad Asif Khan </p> # your name (or website title) here
logo: "/images/best.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="justify">
  I am an aspiring data scientist who is seeking opportunities to solve Big Data problems in cloud computing, finance, and healthcare by using modern tools and technologies of AI and ML.  
  <br>
  I have recently completed M.Sc. Computer Science in Big Data analytics with distinction. It helped me to deepen my knowledge in AI/ML, Advanced Mathematics, Machine Learning, Cloud Computing, Cyber Security, and Database Management. 
  <br>
  I am keen and passionate to build upon my knowledge and continue to learn about new technologies of Big Data. 
  </p>
  <a href="https://www.linkedin.com/in/akhandatascience">View My LinkedIn Profile</a> 
theme: jekyll-theme-minimal 
