title: Muhammad Asif Khan # your name (or website title) here
logo: "/images/best.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 I am a hardworking, passionate, and  fast learning individual who is currently seeking to change my professional career from teaching to Data Science. I am currently enrolled in a Computer Science Masters in Big Data Analytics to deepen my knowledge in software engineering, advanced mathematics, machine learning/AI, cyber security, data analytics, Big Data/IoT technologies and database management. I am very in interested in solving Big Data problems in finance and healthcare by using modern tools and technologies of Machine Learning and Artificial Intelligence. 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
