title: <p align="center"> Muhammad Asif Khan </p> # your name (or website title) here
logo: "/images/best.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="justify">
  I am a data scientist with an excellent knowledge of Machine Learning, Deep Learning Neural Networks, Cloud Computing, Big Data Analytics, Cyber Security, NLP, Advanced Mathematics, and Database Management. I am also a qualified AWS Cloud and ML Practitioner with a solid knowledge of applying  security best practices of core AWS services including SageMaker to build, train, tune and deploy ML models.  
  <br>
  I have recently completed a Master’s in Computer Science in Big Data Analytics with distinction. During the study, I learned about Linear Algebra, Vectors and Statistics; I am able to understand and apply advanced mathematical machine learning models to solve real life problems.
  <br>
  I am currently seeking to change my professional career from teaching to data science. I am very keen to seek opportunities to solve Big Data problems in finance, cloud computing, cyber security and healthcare.  
  <br>
  <a href="https://www.linkedin.com/in/akhandatascience">View My LinkedIn Profile</a> 
  </p>
 
theme: jekyll-theme-minimal 
