title: <p align="center"> Muhammad Asif Khan </p> # your name (or website title) here
logo: "/images/best.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="justify">
  I am an aspiring data scientist who is seeking opportunities to solve Big Data problems in cloud computing, finance, and healthcare by using modern tools and technologies of Artificial Intelligence (AI) and Machine Learning (ML).  
  <br><br>
  I have recently completed a master’s in computer science in Big Data analytics with distinction. It helped me to deepen my knowledge in Big Data/IoT technologies, software engineering, advanced Mathematics, machine learning, deep learning neural networks, cloud computing, cyber security, data analytics, and database management. 
  <br><br>
  I am keen and passionate to build upon my knowledge and continue to learn about new technologies of Big Data. 
  <br><br>
  </p>
  <a href="https://www.linkedin.com/in/akhandatascience">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal 
